# Generated by Django 3.1.4 on 2021-03-07 12:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=225, unique=True, verbose_name='エリア')),
                ('url_code', models.CharField(max_length=50, unique=True, verbose_name='URL名')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='国名')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='お祭りの名前')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='地名')),
                ('start_time', models.CharField(max_length=200, null=True, verbose_name='開催時間')),
                ('thumbnail', models.ImageField(upload_to='img/', verbose_name='サムネイル')),
                ('regist_date', models.DateField(default=datetime.datetime.now, verbose_name='投稿日')),
                ('detail', models.TextField(max_length=400, verbose_name='お祭りの詳細（400文字以内）')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='festival.area', verbose_name='エリア')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='festival.country', verbose_name='国名')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400)),
                ('post_time', models.DateField(auto_now=True)),
                ('author', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='festival.festival', verbose_name='お祭り名')),
            ],
        ),
    ]
